config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcomes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mywedding</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="/assets/style.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Theme Made By www.w3schools.com - No Copyright -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  </head>

  <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">
    <%= yield %>
  </body>
</html>

app/views/welcomes/_form.html.erb
<%= form_with(model: welcome, local: true) do |form| %>
  <% if welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#myPage"><img src="assets/malaijan3.png" style="height: 53px;
      margin-top: -14px;"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#myPage">HOME</a></li>
        <li><a href="#band">With Us</a></li>
        <li><a href="#tour">Events</a></li>
        <li><a href="#contact">CONTACT</a></li>        
      </ul>
    </div>
  </div>
</nav>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="assets/6.jpeg" alt="New York" width="1200" height="700">
      </div>

      <div class="item">
        <img src="assets/7.jpeg" alt="Chicago" width="1200" height="700">
      </div>
    
      <div class="item">
        <img src="assets/8.jpeg" alt="Los Angeles" width="1200" height="700">              
      </div>
      
      <div class="item">
        <img src="assets/6.jpg" alt="Los Angeles" width="1200" height="700">              
      </div>
      <div class="item">
        <img src="assets/3.jpg" alt="Los Angeles" width="1200" height="700">              
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

<!-- Container (The Band Section) -->
<div id="band" class="container text-center">
  <h3>CELEBRATE WITH US</h3>
  <p><em>wE arE geT togetheR!</em></p>

  <p>Hello All,Welcome to our wedding website! Thank you so much for visiting! This is the place you'll find every piece of information you will need regarding our wedding celebration.&nbsp; Our wedding will be taking place in <b>Kokila Thirumana Mandapam,P.Velur, Namakkal on October 30, 2017</b>.</p><p>We look forward to celebrating our wedding with as many friends and family members as possible.</p><p style="text-align: center;"><i>" Love the life you live. Live the life you love" - Bob Marley</i></p>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <p class="text-center"><strong>Malai</strong></p><br>
      <a href="#demo" data-toggle="collapse">
        <img src="assets/left.jpeg" class="img-circle person" alt="Random Name" width="255" height="255">
      </a>
      <div id="demo" class="collapse">
        <p>Malaiyappan Selvam</p>
        <p>DOB: 10 September 1987</p>
      </div>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Malai & Janani</strong></p><br>
      <a href="#demo2" data-toggle="collapse">
        <img src="assets/malaijan.png" class="img-circle person" alt="Random Name" width="255" height="255">
      </a>
      <div id="demo2" class="collapse">
        <p>Kokila Thirumana Mandapam</p>
        <p>Paramathi Velur, Namakkal</p>
        <p>30 October 2017</p>
      </div>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Janani</strong></p><br>
      <a href="#demo3" data-toggle="collapse">
        <img src="assets/right.jpeg" class="img-circle person" alt="Random Name" width="255" height="255" style="width: 51%;">
      </a>
      <div id="demo3" class="collapse">
        <p>Janani Anand</p>
        <p>DOB: 08 June 1993</p>        
      </div>
    </div>
  </div>
</div>

<!-- Container (TOUR Section) -->
<div id="tour" class="bg-1">
  <div class="container">
    <h3 class="text-center">EVENTES TIMINGS </h3>
    <p class="text-center">Remember to book your tickets!</p>
    <div class="row text-center">
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="assets/uruthi.jpg" alt="Paris" width="400" height="300">
          <p><strong>Conformed Our Matches</strong></p>
          <p>Sunday 09 July 2017</p>
          <button class="btn" data-toggle="modal" data-target="#myModal">Mission Completed</button>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="assets/waiting.jpg" alt="New York" width="215" height="300">
          <p><strong>P.VELUR</strong></p>
          <p>Sunday 29 October 2017</p>
          <p>@</p> 
          <p>7pm to 9pm</p>
          <button class="btn" data-toggle="modal" data-target="#myModal">Lock Your Evening</button>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="thumbnail">
          <img src="assets/waiting.jpg" alt="New York" width="215" height="300">
          <p><strong>Kokila Thirumana Mandapam</strong></p>
          <p>Monday 30 October 2017</p>
          <p>@</p>
          <p>11.30am to 2pm </p>
          <button class="btn" data-toggle="modal" data-target="#myModal">Your's Day for Ours</button>
        </div>
      </div>
    </div>
  </div>  
</div>

<!-- Container (Contact Section) -->
<div id="contact" class="container">
  <h3 class="text-center">Connet With Us</h3>
    <p class="text-center"><em><i>We love our Friends!</i></em></p>
  <div class="row">
    <div class="col-md-12 text-center">
      <h4>Friends Contact Us</h4>
      <p><span class="glyphicon glyphicon-map-marker"></span>Namakkal, Tamilnadu</p>
      <p><span class="glyphicon glyphicon-phone"></span>Mobile: +91 9786085148</p>
      <p><span class="glyphicon glyphicon-envelope"></span>Email: smnmalai@gmail.com</p>
    </div>    
  </div>
</div>

<!-- Add Google Maps -->
<div id="googleMap"></div>
<script>
function myMap() {
var myCenter = new google.maps.LatLng(11.112118, 78.0044448);
var mapProp = {center:myCenter, zoom:12, scrollwheel:false, draggable:false, mapTypeId:google.maps.MapTypeId.ROADMAP};
var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
var marker = new google.maps.Marker({position:myCenter});
marker.setMap(map);
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAO43TgFRvWRxe0G4foWDKJYNwYzSGgivQ&callback=myMap"></script>
<!--
To use this code on your website, get a free API key from Google.
Read more at: https://www.w3schools.com/graphics/google_maps_basic.asp
-->

<!-- Footer -->
<footer class="text-center">
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a><br><br>
  <p>Bootstrap Theme Made By <a href="https://www.w3schools.com" data-toggle="tooltip" title="Visit w3schools">www.w3schools.com</a></p> 
</footer>

<script>
$(document).ready(function(){
  // Initialize Tooltip
  $('[data-toggle="tooltip"]').tooltip(); 
  
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {

      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
})
</script>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>